apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-radix
  labels:
    name: parsec-radix
    app: parsec
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:splash2x_radix
        name: parsec-radix
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "CPUSET_PREFIX./run -a run -S splash2x -p radix -i native -n THREAD_COUNT"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "NODE_TYPE"
