apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-dedup
  labels:
    name: parsec-dedup
    app: parsec
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_dedup
        name: parsec-dedup
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "CPUSET_PREFIX./run -a run -S parsec -p dedup -i native -n THREAD_COUNT"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "NODE_TYPE"
