apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: memcached
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args: ["-c", "taskset -c CPUSET ./memcached -t THREADCOUNT -u memcache"]
  nodeSelector:
    cca-project-nodetype: "NODETYPE" 